### ISSUE TITLE
Tracking cabal executables

### ISSUE THREAD

**Issue by lukexi** [commercialhaskell/stack-ide#28] opened 2015-07-18 08:47 UTC
I noticed that stack-ide doesn't seem to track files in executable targets (i.e. when I run `stack ide myproject` it only compiles/reports errors for the "library" section of the cabal file). Is there a way to do this?

(including test-suites would be great too)

**Comment by mgsloan** [comment] 2015-07-18 09:45
I believe this has the same root cause as https://github.com/commercialhaskell/stack/issues/347

While this isn't mentioned there, one thing to try might be to add an `other-modules` list for the executable.  Not sure if that'll fix it, but cabal does support this field for executables / test-suites, though it doesn't demand it.

**Comment by drwebb** [comment] 2015-08-17 04:12
I have the same issue when writing tests (really sucks for TDD). I'm on emacs and stack-mode properly load my tests module either when I run `stack-load-buffer`.

Since https://github.com/commercialhaskell/stack/pull/753 I've been able to run `stack ghci <packagename>:exec:<executable compenent>`. Could the new way stack ghci finds dependencies be added some way to stack-ide?

**Comment by bixuanzju** [comment] 2015-08-17 05:46
For the moment, I am adding an other-modules list for the executable to workaround this, works for me.

**Comment by chrisdone** [comment] 2015-08-17 08:00
I added support for this in `stack ghci`. I'll add it to stack-ide soon.

**Comment by rvion** [comment] 2015-08-17 09:56
as usual, big thanks !

**Comment by carymrobbins** [comment] 2015-09-20 08:55
So does stack-ide only support `library` components currently?

**Comment by chrisdone** [comment] 2015-09-20 10:53
No, it just needs a way in its UI to disambiguate Main modules between components.

**Comment by chrisdone** [comment] 2015-09-20 10:54
https://github.com/commercialhaskell/stack-ide/issues/63

**Comment by chrisdone** [comment] 2015-09-23 14:50
Closing as dupe of #63 which describes the point accurately.

**Closed as completed by chrisdone** 2015-09-23 14:50 UTC
